package clases;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Alumno.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Alumno implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** NumMatricula. */
	private String nummatricula;

	/** Nombre. */
	private String nombre;

	/** FechaNacimiento. */
	private Date fechanacimiento;

	/** Telefono. */
	private String telefono;

	/** The set of Recibe. */
	private Set<Recibe> recibeSet;

	/**
	 * Constructor.
	 */
	public Alumno() {
		this.recibeSet = new HashSet<Recibe>();
	}

	/**
	 * Set the NumMatricula.
	 * 
	 * @param nummatricula
	 *            NumMatricula
	 */
	public void setNummatricula(String nummatricula) {
		this.nummatricula = nummatricula;
	}

	/**
	 * Get the NumMatricula.
	 * 
	 * @return NumMatricula
	 */
	public String getNummatricula() {
		return this.nummatricula;
	}

	/**
	 * Set the Nombre.
	 * 
	 * @param nombre
	 *            Nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the Nombre.
	 * 
	 * @return Nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the FechaNacimiento.
	 * 
	 * @param fechanacimiento
	 *            FechaNacimiento
	 */
	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	/**
	 * Get the FechaNacimiento.
	 * 
	 * @return FechaNacimiento
	 */
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	/**
	 * Set the Telefono.
	 * 
	 * @param telefono
	 *            Telefono
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * Get the Telefono.
	 * 
	 * @return Telefono
	 */
	public String getTelefono() {
		return this.telefono;
	}

	/**
	 * Set the set of the Recibe.
	 * 
	 * @param recibeSet
	 *            The set of Recibe
	 */
	public void setRecibeSet(Set<Recibe> recibeSet) {
		this.recibeSet = recibeSet;
	}

	/**
	 * Add the Recibe.
	 * 
	 * @param recibe
	 *            Recibe
	 */
	public void addRecibe(Recibe recibe) {
		this.recibeSet.add(recibe);
	}

	/**
	 * Get the set of the Recibe.
	 * 
	 * @return The set of Recibe
	 */
	public Set<Recibe> getRecibeSet() {
		return this.recibeSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((nummatricula == null) ? 0 : nummatricula.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Alumno other = (Alumno) obj;
		if (nummatricula == null) {
			if (other.nummatricula != null) {
				return false;
			}
		} else if (!nummatricula.equals(other.nummatricula)) {
			return false;
		}
		return true;
	}

}
