package clases;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of Asignatura.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Asignatura implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** CodAsignatura. */
	private String codasignatura;

	/** Nombre. */
	private String nombre;

	/** Profesor. */
	private Profesor profesor;

	/** The set of Recibe. */
	private Set<Recibe> recibeSet;

	/**
	 * Constructor.
	 */
	public Asignatura() {
		this.recibeSet = new HashSet<Recibe>();
	}

	/**
	 * Set the CodAsignatura.
	 * 
	 * @param codasignatura
	 *            CodAsignatura
	 */
	public void setCodasignatura(String codasignatura) {
		this.codasignatura = codasignatura;
	}

	/**
	 * Get the CodAsignatura.
	 * 
	 * @return CodAsignatura
	 */
	public String getCodasignatura() {
		return this.codasignatura;
	}

	/**
	 * Set the Nombre.
	 * 
	 * @param nombre
	 *            Nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the Nombre.
	 * 
	 * @return Nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the Profesor.
	 * 
	 * @param profesor
	 *            Profesor
	 */
	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	/**
	 * Get the Profesor.
	 * 
	 * @return Profesor
	 */
	public Profesor getProfesor() {
		return this.profesor;
	}

	/**
	 * Set the set of the Recibe.
	 * 
	 * @param recibeSet
	 *            The set of Recibe
	 */
	public void setRecibeSet(Set<Recibe> recibeSet) {
		this.recibeSet = recibeSet;
	}

	/**
	 * Add the Recibe.
	 * 
	 * @param recibe
	 *            Recibe
	 */
	public void addRecibe(Recibe recibe) {
		this.recibeSet.add(recibe);
	}

	/**
	 * Get the set of the Recibe.
	 * 
	 * @return The set of Recibe
	 */
	public Set<Recibe> getRecibeSet() {
		return this.recibeSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codasignatura == null) ? 0 : codasignatura.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Asignatura other = (Asignatura) obj;
		if (codasignatura == null) {
			if (other.codasignatura != null) {
				return false;
			}
		} else if (!codasignatura.equals(other.codasignatura)) {
			return false;
		}
		return true;
	}

}
