package clases;

import java.io.Serializable;

/**
 * Model class of Recibe.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Recibe implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** Alumno. */
	private Alumno alumno;

	/** Asignatura. */
	private Asignatura asignatura;

	/** CursoEscolar. */
	private String cursoescolar;

	/**
	 * Constructor.
	 */
	public Recibe() {
	}

	/**
	 * Set the Alumno.
	 * 
	 * @param alumno
	 *            Alumno
	 */
	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	/**
	 * Get the Alumno.
	 * 
	 * @return Alumno
	 */
	public Alumno getAlumno() {
		return this.alumno;
	}

	/**
	 * Set the Asignatura.
	 * 
	 * @param asignatura
	 *            Asignatura
	 */
	public void setAsignatura(Asignatura asignatura) {
		this.asignatura = asignatura;
	}

	/**
	 * Get the Asignatura.
	 * 
	 * @return Asignatura
	 */
	public Asignatura getAsignatura() {
		return this.asignatura;
	}

	/**
	 * Set the CursoEscolar.
	 * 
	 * @param cursoescolar
	 *            CursoEscolar
	 */
	public void setCursoescolar(String cursoescolar) {
		this.cursoescolar = cursoescolar;
	}

	/**
	 * Get the CursoEscolar.
	 * 
	 * @return CursoEscolar
	 */
	public String getCursoescolar() {
		return this.cursoescolar;
	}


}
